import UIKit

struct StringConstants {
    static let kLblContinue: String = "Continue"
    static let k: String = ""
    static let kLblArabic: String = "Arabic"
    static let kLblEmail: String = "email"
    static let kMsg7ElevenGrocer: String = "7 ELEVEN Grocery Shop"
    static let kMsg2MinAwayBi: String = "2 min away . Birmingham"
    static let kLblLogout: String = "Logout"
    static let kLblEnglish: String = "English"
    static let kMsg5MinAwayBi: String = "5 min away . Birmingham"
    static let kMsgContinueWithE: String = "Continue with Email"
    static let kMsgBySigningUpY2: String = "By signing up you agree to our "
    static let kMsgFloydSBarber: String = "Floyd’s Barber Shop"
    static let kLblGiftConcierge: String = "Gift Concierge"
    static let kLblTermsOfUse: String = "Terms of Use\n"
    static let kLblSearchResult: String = "Search Result"
    static let kMsgNuareRoaster: String = "Nuare | Roastery | Serviced"
    static let kMsgContinueAsAG: String = "Continue as a guest"
    static let kMsgWithARegister: String =
        "With a registered account you can save your\nbusiness and search results, and \nalso receive alerts"
    static let kMsgLetSFindY: String = "Let’s 🔎 find you the \nbest local business 🏭"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblFrench: String = "French"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsg15MinAwayB: String = "15 min away . Birmingham"
    static let kLblBirmingham: String = "Birmingham"
    static let kLblEngland: String = "England"
    static let kLblOrSignWith: String = "Or sign with"
    static let kMsgShoeRestoratio: String = "Shoe Restoration (coming soon)"
    static let kMsgAppVersion11: String = "App version 1.1.0.0.5"
    static let kMsgUnitedArabAmi: String = "United Arab Amirat"
    static let kLblLocation: String = "Location"
    static let kMsgRentalsConci: String = "Rentals & Concierge"
    static let kMsgLetSClarifyY: String = "Let’s clarify your preference"
    static let kMsgWhereAreYouG: String = "Where are you going to search  local business?"
    static let kLblAnd: String = " and "
    static let kMsgBySigningUpY: String =
        "By signing up you agree to our Terms of Use\n and Privacy Policy"
    static let kLblPrivacyPolicy: String = "Privacy Policy"
    static let kMsg1To99Busines: String = "1 to 99 Business Stall  | FENDI"
    static let kLblEditProfile: String = "Edit Profile"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsg10MinAwayB: String = "10 min away . Birmingham"
    static let kMsgServicedAccomm: String = "Serviced Accommodation "
    static let kLblBusinessType: String = "Business Type"
    static let kMsgWhatLanguageD: String = "What language do you prefer?"
    static let kLblRestoration: String = "Restoration "
    static let kLblChangeLocation: String = "Change Location"
    static let kMsgSignInOrRegi: String = "Sign in or Register an account"
}
